### PR TITLE
Added Findx as runner up

### PR DESCRIPTION
**Pull request by brianschildt**
Disclaimer: I loket at the requirements, and since I work at Findx I can't help to mention our initiative.

### CODE REVIEW

**Comment by MathiasRenner** [comment]
@brianschildt Thank you very much for your input! Open Source? Wow, awesome! I wonder why I did not find/recognize your project so far.

However one thing raises questions: You don't track anything. But when clicking on search results, why don't you have direct links and redirect instead:
grafik

(I'll be away during the weekend will answer you probably next week)

**Comment by brianschildt** [comment]
@MathiasRenner Thank you - we are still in beta and struggling a bit to create our own index and get the result relevance to a decent state, which is why we've not made a big fuzz about Findx yet. But we are eager to get all the feedback we can, so please let me know your thoughts.

About the redirect: **Redirect on result click** is a privacy feature, we "obfuscate" the search term when the result is clicked, and the target site will not have the option to track your search term from our referrer link.  We don't use it for tracking, it is how ever optional if you want it, if go to Settings -> Privacy (tab) -> Redirect on result click can be switched on and off.

redirect

Please, if something pops into your mind, I'll be happy to clarify. 

PS: Here is a small [comparison of private search engines](https://www.activateprivacy.com/comparison-of-private-search-engines/) I've made

**Comment by MathiasRenner** [comment]
@brianschildt Hi Brian, I am sorry for my late response! Now I am back :-)
I'll merge the PR in a second, and apply only minor changes afterwards.

I've tried findx in the mean time several times. I like its exceptional speed and lightweight design (compared to e.g. Qwant). It's only the results that are not as good as in e.g. Qwant. I cross my fingers that you create better algorithms here. Looking very much forward to see progress here. If a certain quality threshold is reached, I'll definitely use it as default for myself and spread the word about it.

I might include your search engine comparision into my blog post.

**Comment by MathiasRenner** [comment]
I updated you text a bit, fixed several typos and simplified some expressions. Now you find Findx mentioned the last two chapters. Let me know if you have any more comments on the blog post. And thank you very much again for your input so far!

BTW:
I've seen that you have an app in Google Play store and iOS store (https://get.findx.com/mobile/). As an open source software, you should think about adding the app (primarily) into the f-droid store.

**Pull request merged**
